version: "2"

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - gocritic
    - gosec
    - prealloc
  disable:
    - wrapcheck

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    gosec:
      excludes:
        - G104

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives

    rules:
      - path: _test\.go$
        linters:
          - errcheck
          - gosec

      - path: mock
        linters:
          - all

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  fix: true

run:
  timeout: 5m
  go: "1.23"
